application: billie-pate-69
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
  
- url: .*/third-party
  static_dir: third-party
  
- url: .*/js
  static_dir: js
  
- url: .*/images
  static_dir: images
  
- url: .*/data
  static_dir: data
  
- url: /.*
  script: index.html